#!/usr/bin/env bash
# transfers a file from a client to a server

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path="$1"
	ip="$2"
	username="$3"
	ssh_key="$4"
	scp  -i "$ssh_key" -o StrictHostKeyChecking=no "$file_path" "$username"@"$ip":
fi
