#!/usr/bin/env bash
# script that install nginx on a server
#sudo apt-get update
#sudo apt-get install nginx -y
#echo "Hello World!" > /var/www/html/index.html
#sudo sed -i 's/\blisten\b\s*\b[0-9]\+/\blisten\b 80/' /etc/nginx/sites-available/default
sudo apt-get -y update
sudo apt-get -y install nginx

touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

printf %s "server {
    listen		80 default_server;
        listen		[::]:80 default_server;
	    root		/var/www/html;
	        index		index.html index.htm index.nginx-debian.html;
	}
" > /etc/nginx/sites-available/default

sudo service nginx restart
