#!/usr/bin/env bash
# script that install nginx on a server
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
sudo sed -i 's/\blisten\b\s*\b[0-9]\+/\blisten\b 80/' /etc/nginx/sites-available/default
service nginx restart
