#!/usr/bin/env bash
#configures the server to redirect to another page

apt-get update -y
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen              80 default_server;
    listen              [::]:80 default_server;
    root                /var/www/html;
    index               index.html index.htm index.nginx-debian.html;
    location / {
	add_header X-Served-By $HOSTNAME;
}
    location /redirect_me {
           return 301 https://www.youtube.com/watch?v=TfgBHC5gvTI;
                                }
    error_page 404 /404.html;
    location /404 {
        root /var/www/html/;
        internal;
    }
		}
" > /etc/nginx/sites-available/default
service nginx restart
