#!/usr/bin/env bash
# A script that give information about the file School

name=school
if [ ! -e $name ]
	then
		echo "school file does not exist"
else
	echo "school file exists"
	if [ ! -s $name ]
		then 
			echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ -f $name ]
		then
			echo "school is a regular file"
	else
		echo "school is not a regular file"
	fi
fi
