#!/usr/bin/env bash
#configures nginx to run as nginx user
#it must be listening on all active 8080 ports
adduser --system --no-create-home --disabled-login --group nginx
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/run/nginx
sed -i 's/user  nginx;/user  nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       *:8080;/' /etc/nginx/sites-available/default
service nginx restart
