#!/usr/bin/env bash
#configures nginx to run as nginx user
#it must be listening on all active 8080 ports
adduser --system --no-create-home --disabled-login --group nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
